'use client';
import {useEffect,useState} from 'react'; import {useParams,useRouter} from 'next/navigation'; import {ArrowRight,Copy,LockKeyhole,RefreshCw,Users} from 'lucide-react'; import AppShell from '@/components/AppShell'; import {getSupabase} from '@/lib/supabase';

type GameRow={id:string;name:string;room_code:string;host_id:string;status:string;max_players:number;total_rounds:number;current_round:number;voting_seconds:number;votes_per_player:number};
type PlayerRow={id:string;user_id:string};
export default function RoomPage(){const params=useParams<{code:string}>();const router=useRouter();const [game,setGame]=useState<GameRow|null>(null);const [players,setPlayers]=useState<PlayerRow[]>([]);const [userId,setUserId]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [copied,setCopied]=useState(false);const code=String(params.code||'').toUpperCase();
async function load(){const supabase=getSupabase();if(!supabase){setError('Supabase is not configured.');return}const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/auth');return}setUserId(user.id);const {data:g,error:ge}=await supabase.from('games').select('id,name,room_code,host_id,status,max_players,total_rounds,current_round,voting_seconds,votes_per_player').eq('room_code',code).maybeSingle();if(ge||!g){setError('Room unavailable. Make sure you joined with the correct credentials.');return}setGame(g as GameRow);const {data:p,error:pe}=await supabase.from('game_players').select('id,user_id').eq('game_id',g.id);if(pe){setError(pe.message);return}setPlayers((p||[]) as PlayerRow[])}
useEffect(()=>{load()},[code]);
async function start(){const supabase=getSupabase();if(!supabase||!game)return;setBusy(true);const {data,error}=await supabase.rpc('start_game',{p_game_id:game.id});if(error)setError(error.message);else {setGame({...game,status:'voting',current_round:1});router.push('/vote')}setBusy(false)}
return <AppShell><div className="topbar"><div><div className="eyebrow">PRIVATE ROOM</div><h1 className="page-title">{game?.name||'Loading room…'}</h1><div className="sub">Room {code} · {players.length} / {game?.max_players||'—'} players</div></div><button className="icon-btn" onClick={load} aria-label="Refresh room"><RefreshCw size={16}/></button></div>{error&&<div className="error" style={{marginBottom:16}}>{error}</div>}{game&&<><div className="grid2"><div className="card" style={{padding:24}}><div className="eyebrow">ACCESS</div><h2 className="serif" style={{fontSize:27}}>Private by design.</h2><p className="sub">This room was unlocked using an authenticated account and a valid room password. The password is never displayed or retrievable.</p><div className="actions"><button className="btn light" onClick={async()=>{await navigator.clipboard?.writeText(code);setCopied(true)}}><Copy size={14}/>{copied?'Copied':'Copy room code'}</button></div></div><div className="card" style={{padding:24}}><div className="eyebrow">RULES</div><div style={{display:'grid',gap:12,marginTop:14}}><div><b>{game.votes_per_player}</b><div className="small">Votes per player</div></div><div><b>{Math.round(game.voting_seconds/60)} min</b><div className="small">Voting window</div></div><div><b>{game.total_rounds}</b><div className="small">Rounds</div></div></div></div></div><div className="card" style={{padding:24,marginTop:16}}><div className="topbar" style={{marginBottom:15}}><div><h2 className="serif" style={{fontSize:25}}>Players</h2><div className="small">Only authenticated members can see this room.</div></div>{game.host_id===userId&&game.status==='waiting'&&<button className="btn red" disabled={busy||players.length<3} onClick={start}>{busy?'Starting…':'Start Game'} <ArrowRight size={14}/></button>}</div><div className="grid4">{players.map((p,i)=><div className="player-card" key={p.id}><div className="avatar">{i+1}</div><div style={{marginTop:8,fontWeight:600}}>Player {i+1}</div><div className="small">{p.user_id===game.host_id?'Host':'Member'}</div></div>)}</div>{players.length<3&&<div className="notice">At least 3 players are required before the host can start.</div>}</div></>}</AppShell>}
